baseURL = 'https://vermillion24.github.io/cyber-news/'
languageCode = 'en-us'
title = 'Cyber Intel Hub'
theme = 'terminal'

[params]
    # The 'Terminal' theme looks best in 'orange', 'blue', or 'green'
    themeColor = 'green'
    contentTypeName = 'posts'

# This creates your "About" and "Archive" buttons automatically
[[menu.main]]
    name = "Archive"
    url = "/posts"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
