baseURL = 'https://www.secintel.net/'
languageCode = 'en-us'
title = 'SecIntel | Independent Zero-Day Intelligence Brief'
theme = 'terminal'

[params]
    themeColor = 'green'
    contentTypeName = 'posts'
    fullWidthTheme = false
    maxWidth = "900px"
    showFullContent = true  # <--- This fixes the [] button issue

[[menu.main]]
    name = "Archive"
    url = "/posts"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
